/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/lp/$slug': typeof LpSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/lp/$slug': typeof LpSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/lp/$slug': typeof LpSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cursos/$slug' | '/lp/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cursos/$slug' | '/lp/$slug'
  id: '__root__' | '/' | '/cursos/$slug' | '/lp/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursosSlugRoute: typeof CursosSlugRoute
  LpSlugRoute: typeof LpSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursosSlugRoute: CursosSlugRoute,
  LpSlugRoute: LpSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
